In [ ]:
# Project 5: Systems of linear equations and college football team ranking (with an example of the Big 12)
import numpy as np
from scipy.io import loadmat

In [ ]:
# Load the matrices from .mat files
data_scores = loadmat("Scores.mat")
data_differentials = loadmat("Differentials.mat")
# Extract the relevant matrices
Scores = data_scores['Scores']
Differentials = data_differentials['Differentials']

In [ ]:
# Colley's method
# Define variables
games = np.abs(Scores)
total = np.sum(games, axis=1)
# Construct Colley's matrix and the right-hand side vector
ColleyMatrix = 2 * np.eye(10) + np.diag(total) - games
RightSide = 1 + 0.5 * np.sum(Scores, axis=1)
# Print to verify
print("ColleyMatrix:\n", ColleyMatrix)
print("\nRightSide:\n", RightSide)

ColleyMatrix:
 [[11. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. 11. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. 11. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. 11. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. 11. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. 11. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. 11. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. 11. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. 11. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. 11.]]

RightSide:
 [-0.5 -1.5 -2.5  2.5  5.5  3.5  0.5 -0.5 -0.5  2.5]


In [ ]:
# Solve the linear system using np.linalg.solve
RanksColley = np.linalg.solve(ColleyMatrix, RightSide)
# Variables: RanksColley
print("RanksColley:\n", RanksColley)

RanksColley:
 [0.33333333 0.25       0.16666667 0.58333333 0.83333333 0.66666667
 0.41666667 0.33333333 0.33333333 0.58333333]


In [ ]:
# Teams list
Teams = [
'Baylor', 'Iowa State', 'University of Kansas', 'Kansas State',
'University of Oklahoma', 'Oklahoma State', 'Texas Christian',
'University of Texas Austin', 'Texas Tech', 'West Virginia'
]
# Sort the ranks in descending order and get the order of indices
Order = np.argsort(RanksColley)[::-1]
RanksDescend = RanksColley[Order]
# Display the results
print('\n')
for j in range(10):
    print(f'{RanksColley[Order[j]]:8.3f} {Teams[Order[j]]:15s}')



   0.833 University of Oklahoma
   0.667 Oklahoma State 
   0.583 Kansas State   
   0.583 West Virginia  
   0.417 Texas Christian
   0.333 Baylor         
   0.333 Texas Tech     
   0.333 University of Texas Austin
   0.250 Iowa State     
   0.167 University of Kansas


In [ ]:
# Massey's method
l = 0
P = []
B = []
# Loop through the upper triangular part of the Differentials matrix
for j in range(9):
    for k in range(j + 1, 10):
        if Differentials[j, k] != 0:
            l += 1
            row = np.zeros(10)
            row[j] = 1
            row[k] = -1
            P.append(row)
            B.append(Differentials[j, k])
# Convert lists to numpy arrays
P = np.array(P)
B = np.array(B)
# Variables: P, B
print("Matrix P:\n", P)
print("Vector B:\n", B)

Matrix P:
 [[ 1. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0. -1.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  1. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0. -1.  0.]


In [ ]:
# Create the normal system of linear equations
A = np.dot(P.T, P)
D = np.dot(P.T, B)
# Variables: A, D
print("Matrix A:\n", A)
print("Vector D:\n", D)

Matrix A:
 [[ 9. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1.  9. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1.  9. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1.  9. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1.  9. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  9. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.  9. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.  9. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  9. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.  9.]]
Vector D:
 [ -49.  -34. -202.   45.  169.   70.    2.  -25.  -51.   75.]


In [ ]:
# Substitute the last row of the matrix and the last element of the vector
A[9, :] = np.ones(10)
D[9] = 0
# Print the updated matrix and vector
print("Updated Matrix A:\n", A)
print("Updated Vector D:\n", D)

Updated Matrix A:
 [[ 9. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1.  9. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1.  9. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1.  9. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1.  9. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  9. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.  9. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.  9. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  9. -1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
Updated Vector D:
 [ -49.  -34. -202.   45.  169.   70.    2.  -25.  -51.    0.]


In [ ]:
# Solve the system
RanksMassey = np.linalg.solve(A, D)
# Print the results
print("RanksMassey:\n", RanksMassey)

RanksMassey:
 [ -4.9  -3.4 -20.2   4.5  16.9   7.    0.2  -2.5  -5.1   7.5]


In [ ]:
# Teams list
Teams = ['Baylor', 'Iowa State', 'University of Kansas', 'Kansas State',
'University of Oklahoma', 'Oklahoma State', 'Texas Christian',
'University of Texas Austin', 'Texas Tech', 'West Virginia']
# Sort the ranks in descending order
Order = np.argsort(RanksMassey)[::-1]
RanksDescend = RanksMassey[Order]
# Print the results
print("\nMassey Rankings:")
for j in range(10):
    print(f'{RanksDescend[j]:8.3f} {Teams[Order[j]]:<15}')


Massey Rankings:
  16.900 University of Oklahoma
   7.500 West Virginia  
   7.000 Oklahoma State 
   4.500 Kansas State   
   0.200 Texas Christian
  -2.500 University of Texas Austin
  -3.400 Iowa State     
  -4.900 Baylor         
  -5.100 Texas Tech     
 -20.200 University of Kansas


In [ ]:
print("Compare results of past 2 tasks")

Compare results of past 2 tasks


In [ ]:
# Identify the current top two teams according to Colley's rankings
top_teams_colley = sorted(range(len(RanksColley)), key=lambda i: RanksColley[i],
reverse=True)[:2]
# Simulate switching the result of the game between the top two teams
# For example, if team 0 (top_teams_colley[0]) played against team 1 (top_teams_colley[1])
# and team 0 lost, we switch it to a win.
Scores[top_teams_colley[0], top_teams_colley[1]] = -Scores[top_teams_colley[0],
top_teams_colley[1]]
# Recalculate Colley's rankings
games = np.abs(Scores)
total = np.sum(games, axis=1)
ColleyMatrix = 2 * np.eye(10) + np.diag(total) - games
RightSide = (1 + 0.5 * np.sum(Scores, axis=1))
RanksColley_updated = np.linalg.solve(ColleyMatrix, RightSide)
# Display the updated rankings
teams = ['Baylor', 'Iowa State', 'University of Kansas', 'Kansas State',
'University of Oklahoma', 'Oklahoma State', 'Texas Christian',
'University of Texas Austin', 'Texas Tech', 'West Virginia']
# Sort and print rankings
order_updated = np.argsort(RanksColley_updated)[::-1]
print("\nUpdated Colley's Rankings After Game Result Switch:")
for j in range(10):
    print(f"{RanksColley_updated[order_updated[j]]:8.3f} {teams[order_updated[j]]}")
# Reset the game result for future calculations
Scores[top_teams_colley[0], top_teams_colley[1]] = -Scores[top_teams_colley[0],
top_teams_colley[1]]


Updated Colley's Rankings After Game Result Switch:
   0.708 University of Oklahoma
   0.625 Oklahoma State
   0.542 Kansas State
   0.542 West Virginia
   0.375 Texas Christian
   0.292 Baylor
   0.292 Texas Tech
   0.292 University of Texas Austin
   0.208 Iowa State
   0.125 University of Kansas


In [ ]:
# Identify the current top two teams according to Massey's rankings
top_teams_massey = sorted(range(len(RanksMassey)), key=lambda i: RanksMassey[i],
reverse=True)[:2]
# Simulate switching the result of the game between the top two teams for Massey's method
# Adjust the differential matrix Differentials for the switched game result
# For example, if team 0 (top_teams_massey[0]) played against team 1
(top_teams_massey[1])
# and team 0 lost, we switch it to a win.
if Differentials[top_teams_massey[0], top_teams_massey[1]] != 0:
    Differentials[top_teams_massey[0], top_teams_massey[1]] = - Differentials[top_teams_massey[0], top_teams_massey[1]]
# Reset the initial matrix P to be large enough to accommodate all possible rows
P = np.zeros((45, 10))
B = np.zeros(45)
l = -1 # Initialize l to -1 because it will be incremented at the beginning of the loop
# Populate P and B based on the conditionals in your loop
for j in range(9):
    for k in range(j + 1, 10):
        if Differentials[j, k] != 0:
            l += 1
            P[l, j] = 1
            P[l, k] = -1
            B[l] = Differentials[j, k]
# Adjust for the last row substitution as described in the previous steps
P[44, :] = np.ones(10)
B[44] = 0
# Recalculate Massey's rankings
A = np.dot(P.T, P)
D = np.dot(P.T, B)
# Solve the system again
RanksMassey_updated = np.linalg.solve(A, D)
# Display the updated rankings
print("\nUpdated Massey's Rankings After Game Result Switch:")
order_updated_massey = np.argsort(RanksMassey_updated)[::-1]
for j in range(10):
    print(f"{RanksMassey_updated[order_updated_massey[j]]:8.3f} {teams[order_updated_massey[j]]}")
# Reset the game result for future calculations
if Differentials[top_teams_massey[0], top_teams_massey[1]] != 0:
    Differentials[top_teams_massey[0], top_teams_massey[1]] = - Differentials[top_teams_massey[0], top_teams_massey[1]]


Updated Massey's Rankings After Game Result Switch:
  11.500 West Virginia
  11.300 University of Oklahoma
   7.000 Oklahoma State
   4.500 Kansas State
   0.200 Texas Christian
  -2.500 University of Texas Austin
  -3.400 Iowa State
  -3.500 Texas Tech
  -4.900 Baylor
 -20.200 University of Kansas
