In [ ]:
# Project 4: Solving linear systems in Python
import numpy as np
import time

In [ ]:
# Define a function to create a magic-like matrix
def create_magic_like(n):
    magic_square = np.zeros((n, n), dtype=int)
    row, col = 0, n // 2
    num = 1
    while num <= n*n:
        magic_square[row, col] = num
        num += 1
        new_row, new_col = (row - 1) % n, (col + 1) % n
        if magic_square[new_row,new_col]:
            row += 1
        else:
            row, col = new_row, new_col
    return magic_square
# Generate a 5x5 "magic- like" matrix
A = create_magic_like(5)
# Define column vector b
b = np.array([10, 26, 42, 59,
38])
# Print matrix A and vector b
print("Matrix A:")
print(A)
print("\nVector b:", b)

Matrix A:
[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]

Vector b: [10 26 42 59 38]


In [ ]:
# Solve the system Ax = b using numpy's solve function
x = np.linalg.solve(A, b)
# Print the solution vector x
print("Solution vector x:\n")
print(x)

Solution vector x:

[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]


In [ ]:
# Calculate the residual r = A*x - b
r = np.dot(A, x) - b
# Print the residual vector r
print("\nResidual vector r:")
print(r)


Residual vector r:
[ 0.00000000e+00  3.55271368e-15  0.00000000e+00  0.00000000e+00
 -7.10542736e-15]


In [ ]:
import scipy.linalg
# Perform LU decomposition of A
P, L, U = scipy.linalg.lu(A) # Note: Use scipy.linalg.lu for LU decomposition
# Solve the system Ax = b using LU decomposition
x1 = np.linalg.solve(A, b)
# Calculate the error between solutions
err1 = np.dot(A, x1) - b
# Print matrices P, L, U and vectors x1, err1
print("Matrix P (Permutation matrix):")
print(P)
print("\nMatrix L (Lower triangular matrix):")
print(L)
print("\nMatrix U (Upper triangular matrix):")
print(U)
print("\nSolution vector x1:")
print(x1)
print("\nError vector err1:")
print(err1)

Matrix P (Permutation matrix):
[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

Matrix L (Lower triangular matrix):
[[1.         0.         0.         0.         0.        ]
 [0.73913043 1.         0.         0.         0.        ]
 [0.47826087 0.76873662 1.         0.         0.        ]
 [0.17391304 0.25267666 0.5163652  1.         0.        ]
 [0.43478261 0.48394004 0.72308355 0.92307692 1.        ]]

Matrix U (Upper triangular matrix):
[[ 23.           5.           7.          14.          16.        ]
 [  0.          20.30434783  -4.17391304  -2.34782609   3.17391304]
 [  0.           0.          24.8608137   -2.89079229  -1.09207709]
 [  0.           0.           0.          19.65116279  18.97932817]
 [  0.           0.           0.           0.         -22.22222222]]

Solution vector x1:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Error vector err1:
[ 0.00000000e+00  3.55271368e-15  0.00000000e+00  0.00000000e+00
 -7.

In [ ]:
# Solve the system Ax = b using numpy's least squares function
y = np.linalg.lstsq(A, b, rcond=None)[0]
# Print the solution vector y
print("\nSolution vector y:")
print(y)


Solution vector y:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]


In [ ]:
# Solve the system Ax = b using matrix inverse
A_inv = np.linalg.inv(A)
x2 = np.dot(A_inv, b)
# Calculate the residual r2 and error err2
r2 = np.dot(A, x2) - b
err2 = x - x2
# Print solution vector x2, residual r2 and error err2
print("\nSolution vector x2 using inverse:")
print(x2)
print("\nResidual vector r2:")
print(r2)
print("\nError vector err2:")
print(err2)


Solution vector x2 using inverse:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Residual vector r2:
[-3.55271368e-15 -3.55271368e-15 -7.10542736e-15  0.00000000e+00
 -7.10542736e-15]

Error vector err2:
[-7.63278329e-17  4.16333634e-17  0.00000000e+00  4.44089210e-16
  5.55111512e-17]


In [ ]:
def rref(A):
    '''
    Computes the reduced row echelon
    form (RREF) of a matrix A.
    Parameters:
    A : numpy.ndarray
    Input matrix of shape (m, n)
    Returns:
    R : numpy.ndarray
    Reduced row echelon form of matrix
    A
    '''
    A = A.astype(float)
    m, n = A.shape
    lead = 0
    for r in range(m):
        if lead >= n:
            break
        if A[r, lead] == 0:
            for i in range(r + 1, m):
                if A[i, lead] != 0:
                    A[[r, i]] = A[[i, r]]
                    break
        if A[r, lead] != 0:
            A[r] = A[r] / A[r, lead]
        for i in range(m):
            if i != r:
                A[i] -= A[i, lead] * A[r]
        lead += 1
    return A
# Compute reduced row echelon form of [A | b]
C = np.hstack((A, b[:, np.newaxis]))
R = rref(C)
# Extract solution vector x3 from the RREF matrix
x3 = R[:, -1]
# Calculate residuals
r3 = np.dot(A, x3) - b
err3 = x - x3
print("\nSolution vector x3 (from RREF):")
print(x3)
print("\nResidual vector r3 (from RREF):")
print(r3)
print("\nError vector err3 (differencebetween x and x3):")
print(err3)


Solution vector x3 (from RREF):
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Residual vector r3 (from RREF):
[1.77635684e-15 7.10542736e-15 0.00000000e+00 2.13162821e-14
 0.00000000e+00]

Error vector err3 (differencebetween x and x3):
[-2.67147415e-16  9.71445147e-17  0.00000000e+00 -4.44089210e-16
  2.22044605e-16]


In [ ]:
# Initialize Num
Num = 500
# Generate matrix A and vector b
A = np.random.rand(Num, Num) + Num * np.eye(Num)
b = np.random.rand(Num, 1)
# Method 1: Solve using backslash operator
start_time = time.time()
x1 = np.linalg.solve(A, b)
end_time = time.time()
time_backslash = end_time - start_time
# Method 2: Solve using matrix inverse
start_time = time.time()
x2 = np.linalg.inv(A) @ b
end_time = time.time()
time_inv = end_time - start_time
# Method 3: Solve using reduced row echelon form (rref)
start_time = time.time()
C = np.hstack((A, b))
R = rref(C)
x3 = R[:, -1]
end_time = time.time()
time_rref = end_time - start_time
# Print the solution vectors and computational times
print("\nSolution vector x1 (using backslash operator):")
print(x1)
print("\nSolution vector x2 (using matrix inverse):")
print(x2)
print("\nSolution vector x3 (using reduced row echelon form):")
print(x3)
print("\nComputational times:")
print(f"Backslash operator: {time_backslash} seconds")
print(f"Matrix inverse: {time_inv} seconds")
print(f"Reduced row echelon form (rref): {time_rref} seconds")


Solution vector x1 (using backslash operator):
[[ 8.13689836e-04]
 [ 5.72249880e-04]
 [ 7.46138902e-04]
 [ 8.76282108e-04]
 [-2.43766168e-04]
 [ 1.56814431e-03]
 [ 8.24181765e-04]
 [ 5.62612934e-04]
 [ 9.54249856e-04]
 [-2.74846419e-04]
 [ 1.56752730e-03]
 [ 1.39122957e-03]
 [ 1.08610058e-03]
 [ 1.11972171e-03]
 [ 1.15455113e-04]
 [ 5.45253327e-04]
 [ 6.96229903e-04]
 [ 9.02733433e-04]
 [ 5.30937392e-04]
 [-2.49231317e-04]
 [-1.98283836e-04]
 [ 1.06088965e-03]
 [ 4.13918726e-04]
 [ 1.19944690e-03]
 [ 1.33975682e-03]
 [-8.99751326e-05]
 [ 1.39277011e-03]
 [ 1.60317361e-03]
 [ 1.53927974e-03]
 [ 4.08278740e-04]
 [ 8.83855056e-04]
 [ 1.13407772e-03]
 [-2.86196030e-04]
 [ 8.59412131e-04]
 [ 1.03159067e-03]
 [ 1.28606242e-03]
 [-2.54775971e-04]
 [ 9.94221198e-04]
 [ 5.66920873e-04]
 [ 3.63744372e-04]
 [ 2.82154776e-04]
 [ 9.63779513e-04]
 [ 9.81465128e-04]
 [ 3.83066412e-04]
 [ 7.53600079e-04]
 [ 2.41800574e-04]
 [-3.91501009e-05]
 [ 6.22196542e-05]
 [-1.03337131e-04]
 [ 3.62511652e-04]
 [

In [ ]:
# Define matrix A and vector b forthe overdetermined system
A = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 10],
                [9, 11, 12]])

b = np.array([1, 2, 3, 4]).reshape(-1, 1) # Reshape b to be a columnvector
# Solve the system Ax = b using the backslash operator
x = np.linalg.lstsq(A, b,
rcond=None)[0]
# Calculate the residual r = Ax - b
r = np.dot(A, x) - b
# Print the solution vector x
print("\nSolution vector x:")
print(x)
# Print the residual vector r
print("\nResidual vector r:")
print(r)
# Calculate and print the solution using normal equations for comparison
ATA_inv = np.linalg.inv(np.dot(A.T,A)) # Calculate (A.T * A)^(-1)
ATb = np.dot(A.T, b) #Calculate A.T * b
y = np.dot(ATA_inv, ATb) #Solve normal equations A.T * A * y= A.T * b
# Calculate the difference between x and y to verify accuracy
err = x - y
# Print the solution vector y from normal equations
print("\nSolution vector y (from normal equations):")
print(y)
# Print the difference vector err (should be close to zero)
print("\nDifference vector err (x - y):")
print(err)


Solution vector x:
[[-0.24630542]
 [ 0.38916256]
 [ 0.16256158]]

Residual vector r:
[[ 0.01970443]
 [-0.06403941]
 [ 0.01477833]
 [ 0.01477833]]

Solution vector y (from normal equations):
[[-0.24630542]
 [ 0.38916256]
 [ 0.16256158]]

Difference vector err (x - y):
[[-1.13797860e-15]
 [-3.75255382e-14]
 [ 1.19071419e-14]]


In [ ]:
# Define matrix A and vector b for the underdetermined system
A = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
[10, 11, 12]])
b = np.array([1, 3, 5, 7]).reshape(-1, 1) #Remove the reshape, as it's unnecessary
# Solve the system Ax = b using the backslash operator
x = np.linalg.lstsq(A, b, rcond=None)[0]
# Calculate the residual r1 = Ax - b
r1 = np.dot(A, x) - b
# Print the solution vector x
print("\nSolution vector x:")
print(x)
# Print the residual vector r1
print("\nResidual vector r1:")
print(r1)
# Obtain another particular solution using the pseudoinverse pinv(A)
A_pinv = np.linalg.pinv(A)
y = np.dot(A_pinv, b)
# Calculate the residual r2 = Ax - b for solution y
r2 = np.dot(A, y) - b
# Print the solution vector y from pseudoinverse
print("\nSolution vector y (from pseudoinverse):")
print(y)
# Print the residual vector r2
print("\nResidual vector r2:")
print(r2)


Solution vector x:
[[0.38888889]
 [0.22222222]
 [0.05555556]]

Residual vector r1:
[[8.8817842e-16]
 [8.8817842e-16]
 [8.8817842e-16]
 [0.0000000e+00]]

Solution vector y (from pseudoinverse):
[[0.38888889]
 [0.22222222]
 [0.05555556]]

Residual vector r2:
[[ 1.55431223e-15]
 [-4.44089210e-16]
 [-2.66453526e-15]
 [-4.44089210e-15]]
