In [ ]:
# Project 1: Basic operations with matrices in Python
import numpy as np

In [ ]:
A = np.array([[1, 2, -10, 4], [3, 4, 5, -6], [3, 3, -2, 5]])
B = np.array([3, 3, 4, 2])
print("A:\n", A)
print("B:\n", B)

A:
 [[  1   2 -10   4]
 [  3   4   5  -6]
 [  3   3  -2   5]]
B:
 [3 3 4 2]


In [ ]:
#function to determine length
def length(matrix):
    return max(matrix.shape)

# Length of A and B
lengthA = length(A)
lengthB = length(B)
print("lengthA:", lengthA)
print("lengthB:", lengthB)

lengthA: 4
lengthB: 4


In [ ]:
# Add B as the fourth row of A and create the new matrix C
C = np.vstack((A, B))
print("C:\n", C)

C:
 [[  1   2 -10   4]
 [  3   4   5  -6]
 [  3   3  -2   5]
 [  3   3   4   2]]


In [ ]:
# Create D from rows 2, 3, 4 and columns 3, 4 of C
D = C[1:4, 2:4]
print("D:\n", D)

D:
 [[ 5 -6]
 [-2  5]
 [ 4  2]]


In [ ]:
# Transpose D to create E
E = D.T
print("E:\n", E)

E:
 [[ 5 -2  4]
 [-6  5  2]]


In [ ]:
# Check the size of E
m, n = E.shape
print("m:", m)
print("n:", n)

m: 2
n: 3


In [ ]:
# Create equally spaced vectors using arange and linspace
EqualSpaced = np.arange(0, 2 * np.pi, np.pi / 10)
EqualSpaced1 = np.linspace(0, 2 * np.pi, 21)
print("EqualSpaced:\n", EqualSpaced)
print("EqualSpaced1:\n", EqualSpaced1)

EqualSpaced:
 [0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265 3.45575192
 3.76991118 4.08407045 4.39822972 4.71238898 5.02654825 5.34070751
 5.65486678 5.96902604]
EqualSpaced1:
 [0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265 3.45575192
 3.76991118 4.08407045 4.39822972 4.71238898 5.02654825 5.34070751
 5.65486678 5.96902604 6.28318531]


In [ ]:
# Find the maximum and minimum in each column of A
maxcolA = np.max(A, axis=0)
mincolA = np.min(A, axis=0)
print("maxcolA:", maxcolA)
print("mincolA:", mincolA)

maxcolA: [3 4 5 5]
mincolA: [  1   2 -10  -6]


In [ ]:
# Find the maximum and minimum in each row of A
maxrowA = np.max(A, axis=1)
minrowA = np.min(A, axis=1)
# Find the maximum and minimum elements in the entire matrix A
maxA = np.max(A)
minA = np.min(A)
print("maxrowA:", maxrowA)
print("minrowA:", minrowA)
print("maxA:", maxA)
print("minA:", minA)

maxrowA: [4 5 5]
minrowA: [-10  -6  -2]
maxA: 5
minA: -10


In [ ]:
# Calculate mean and sum in each column and row of A
meancolA = np.mean(A, axis=0)
meanrowA = np.mean(A, axis=1)
sumcolA = np.sum(A, axis=0)
sumrowA = np.sum(A, axis=1)
# Calculate mean and sum of all elements in A
meanA = np.mean(A)
sumA = np.sum(A)
print("meancolA:", meancolA)
print("meanrowA:", meanrowA)
print("sumcolA:", sumcolA)
print("sumrowA:", sumrowA)
print("meanA:", meanA)
print("sumA:", sumA)

meancolA: [ 2.33333333  3.         -2.33333333  1.        ]
meanrowA: [-0.75  1.5   2.25]
sumcolA: [ 7  9 -7  3]
sumrowA: [-3  6  9]
meanA: 1.0
sumA: 12


In [ ]:
# Create matrices F and G with random integers from -4 to 4
F = np.random.randint(-4, 5, (5, 3))
G = np.random.randint(-4, 5, (5, 3))
print("F:\n", F)
print("G:\n", G)

F:
 [[-2 -4  2]
 [ 2 -4 -2]
 [ 4  2  3]
 [ 0  3 -1]
 [-4  4  1]]
G:
 [[ 1  0  0]
 [ 0  2  0]
 [ 1  2 -4]
 [-3 -1 -4]
 [ 0  4 -4]]


In [ ]:
# Perform scalar multiplication, addition, subtraction, and element-wise multiplication on F and G
ScMultF = 0.4 * F
SumFG = F + G
DiffFG = F - G
ElProdFG = F * G
print("ScMultF:\n", ScMultF)
print("SumFG:\n", SumFG)
print("DiffFG:\n", DiffFG)
print("ElProdFG:\n", ElProdFG)

ScMultF:
 [[-0.8 -1.6  0.8]
 [ 0.8 -1.6 -0.8]
 [ 1.6  0.8  1.2]
 [ 0.   1.2 -0.4]
 [-1.6  1.6  0.4]]
SumFG:
 [[-1 -4  2]
 [ 2 -2 -2]
 [ 5  4 -1]
 [-3  2 -5]
 [-4  8 -3]]
DiffFG:
 [[-3 -4  2]
 [ 2 -6 -2]
 [ 3  0  7]
 [ 3  4  3]
 [-4  0  5]]
ElProdFG:
 [[ -2   0   0]
 [  0  -8   0]
 [  4   4 -12]
 [  0  -3   4]
 [  0  16  -4]]


In [ ]:
# Check the size of F and A
sizeF = F.shape
sizeA = A.shape
print("sizeF:", sizeF)
print("sizeA:", sizeA)

sizeF: (5, 3)
sizeA: (3, 4)


In [ ]:
# Perform matrix multiplication of F and A if dimensions are compatible
if sizeF[1] == sizeA[0]:
    H = F @ A
    print("H:\n", H)
else:
    print("Cannot multiply F and A due to incompatible dimensions.")

H:
 [[ -8 -14  -4  26]
 [-16 -18 -36  22]
 [ 19  25 -36  19]
 [  6   9  17 -23]
 [ 11  11  58 -35]]


In [ ]:
# Generate the identity matrix with 3 rows and 3 columns
eye33 = np.eye(3)
print("eye33:\n", eye33)

eye33:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Generate matrices of zeros with size 5x3 and ones with size 4x2
zeros53 = np.zeros((5, 3))
ones42 = np.ones((4, 2))
print("zeros53:\n", zeros53)
print("ones42:\n", ones42)

zeros53:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones42:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Generate a diagonal matrix S with the diagonal elements 1, 2, 7
S = np.diag([1, 2, 7])
print("S:\n", S)

S:
 [[1 0 0]
 [0 2 0]
 [0 0 7]]


In [ ]:
# Extract the diagonal elements from a random 6x6 matrix
R = np.random.rand(6, 6)
diagR = np.diag(R)
print("R:", R)
print("diagR:", diagR)

R: [[0.40151202 0.62282625 0.35680583 0.01422376 0.05999239 0.32926742]
 [0.10496773 0.99996929 0.95455657 0.29959249 0.6798288  0.15754804]
 [0.39796597 0.07202853 0.43580223 0.25549625 0.77360268 0.52160439]
 [0.01999679 0.75971532 0.98973635 0.8658178  0.71202421 0.90482223]
 [0.79462579 0.37573559 0.46681164 0.18296374 0.87420623 0.53091008]
 [0.05852918 0.53290773 0.23654192 0.14048134 0.69536968 0.92474325]]
diagR: [0.40151202 0.99996929 0.43580223 0.8658178  0.87420623 0.92474325]


In [ ]:
# Create a sparse diagonal matrix and convert to dense
from scipy.sparse import diags
diag121 = diags([-np.ones(10), 2*np.ones(10), -np.ones(10)], [-1, 0, 1], shape=(10,
10)).todense()
print("diag121:\n", diag121)

diag121:
 [[ 2. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  2.]]
